### ISSUE TITLE
Its not starting

### ISSUE THREAD

**Issue by junaidrahim** [abhijithnraj/Mario#1]
I did `python3 main.py` and this showed up

```shell
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from goomba import *
  File "/home/junaidrahim/Sandbox/Mario/goomba.py", line 66, in <module>
    images=cut_image("images/goomba.png",n_x=9,n_y=6,position=2)
  File "/home/junaidrahim/Sandbox/Mario/functions.py", line 27, in cut_image
    sheet = pygame.image.load("images/new.png").convert_alpha()
pygame.error: cannot convert without pygame.display initialized
```
How do I start the game ?

**Comment by abhijithnraj** [comment]
I have not yet completed the game. But I have fixed this issue for video error. I think it crept in from the newer version of pygame. Just type in python3 main.py and you can see the goomba functionality. I have been meaning to complete this project for a while now. Anyway will do soon.

**Comment by abhijithnraj** [comment]
I will also be reviewing pull requests gladly :) . So Please don't be hesitant to Send a pull request if you are also working on it.

**Comment by abhijithnraj** [comment]
![image](https://user-images.githubusercontent.com/23445617/46251862-b6671d80-c47c-11e8-9226-7bb19f376c32.png)

**Comment by junaidrahim** [comment]
Ok, will try now. Thanks
